export const data = JSON.parse("{\"key\":\"v-0689d3ea\",\"path\":\"/abstract/introduction.html\",\"title\":\"实验室简介\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"circle-info\",\"cover\":\"/assets/images/cover3.jpg\",\"description\":\"实验室简介 近年来以深度学习为代表的机器学习理论、方法和技术得到迅猛发展，为大数据时代挖掘、发现和利用数据的有效价值提供了一把金钥匙，也使得计算机获得了前所未有的感知能力。以机器学习为代表的人工智能技术正在掀起可以媲美工业革命的智能革命，各行业、学科领域均不可避免地卷入到这一科技革命的洪涛巨浪中，如何使培养的学生能够站在当前的科技革命浪潮之巅，成为时代的弄潮儿是本实验室的培养目标和宗旨。近两年实验室培养的研究生主要就业去向有阿里巴巴、百度、腾讯、唯品会、国家电网、证券公司、银行、华为、中兴、高校和科研院所、通信运营商等各类企事业单位。 实验室的学术带头人是丁兴号教授、博导、福建省百千万人才、福建省新世纪优秀人才、智慧城市感知与计算福建省重点实验室副主任。成员有黄悦教授、肖珍龙副教授、涂晓彤助理教授。同时实验室与美国一流高校如卡内基梅隆大学、哥伦比亚大学、杜克大学、德州大学奥斯汀分校、罗切斯特大学等研究团队保持密切的合作研究，为实验室营造与国际一流高校的机器学习和大数据分析团队合作开展研究和联合培养研究生的氛围。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://xmu-smartdsp.github.io/abstract/introduction.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"厦门大学智能数据分析与处理实验室\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"实验室简介\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"实验室简介 近年来以深度学习为代表的机器学习理论、方法和技术得到迅猛发展，为大数据时代挖掘、发现和利用数据的有效价值提供了一把金钥匙，也使得计算机获得了前所未有的感知能力。以机器学习为代表的人工智能技术正在掀起可以媲美工业革命的智能革命，各行业、学科领域均不可避免地卷入到这一科技革命的洪涛巨浪中，如何使培养的学生能够站在当前的科技革命浪潮之巅，成为时代的弄潮儿是本实验室的培养目标和宗旨。近两年实验室培养的研究生主要就业去向有阿里巴巴、百度、腾讯、唯品会、国家电网、证券公司、银行、华为、中兴、高校和科研院所、通信运营商等各类企事业单位。 实验室的学术带头人是丁兴号教授、博导、福建省百千万人才、福建省新世纪优秀人才、智慧城市感知与计算福建省重点实验室副主任。成员有黄悦教授、肖珍龙副教授、涂晓彤助理教授。同时实验室与美国一流高校如卡内基梅隆大学、哥伦比亚大学、杜克大学、德州大学奥斯汀分校、罗切斯特大学等研究团队保持密切的合作研究，为实验室营造与国际一流高校的机器学习和大数据分析团队合作开展研究和联合培养研究生的氛围。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://xmu-smartdsp.github.io/assets/images/cover3.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"实验室简介\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"SmartDSP\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"实验室简介\\\",\\\"image\\\":[\\\"https://xmu-smartdsp.github.io/assets/images/cover3.jpg\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"SmartDSP\\\",\\\"url\\\":\\\"https://xmu-smartdsp.github.io/\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.13,\"words\":638},\"filePathRelative\":\"abstract/introduction.md\",\"excerpt\":\"<h1> 实验室简介</h1>\\n<p>近年来以深度学习为代表的机器学习理论、方法和技术得到迅猛发展，为大数据时代挖掘、发现和利用数据的有效价值提供了一把金钥匙，也使得计算机获得了前所未有的感知能力。以机器学习为代表的人工智能技术正在掀起可以媲美工业革命的智能革命，各行业、学科领域均不可避免地卷入到这一科技革命的洪涛巨浪中，如何使培养的学生能够站在当前的科技革命浪潮之巅，成为时代的弄潮儿是本实验室的培养目标和宗旨。近两年实验室培养的研究生主要就业去向有阿里巴巴、百度、腾讯、唯品会、国家电网、证券公司、银行、华为、中兴、高校和科研院所、通信运营商等各类企事业单位。</p>\\n<p>实验室的学术带头人是丁兴号教授、博导、福建省百千万人才、福建省新世纪优秀人才、智慧城市感知与计算福建省重点实验室副主任。成员有黄悦教授、肖珍龙副教授、涂晓彤助理教授。同时实验室与美国一流高校如卡内基梅隆大学、哥伦比亚大学、杜克大学、德州大学奥斯汀分校、罗切斯特大学等研究团队保持密切的合作研究，为实验室营造与国际一流高校的机器学习和大数据分析团队合作开展研究和联合培养研究生的氛围。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
