export const pagesRoutes = [
  ["v-6d34f632","/contact.html",{"y":"p","t":"联系我们","i":"circle-info"},[":md"]],
  ["v-5690e415","/graduate.html",{"y":"p","t":"桃李天下","i":"circle-info"},[":md"]],
  ["v-184f4da6","/intro.html",{"y":"p","t":"介绍页","i":"circle-info"},[":md"]],
  ["v-52062726","/introduction.html",{"y":"p","t":"实验室简介","i":"circle-info"},[":md"]],
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/README.md"]],
  ["v-cf4e0fda","/research-direction.html",{"y":"p","t":"研究方向","i":"circle-info"},[":md"]],
  ["v-1d79747a","/team.html",{"y":"p","t":"学术团队","i":"circle-info"},[":md"]],
  ["v-636b64bf","/dataset/OptimusPrime.html",{"y":"p","t":"The Optimus Prime dataset","i":"pen-to-square"},[":md"]],
  ["v-fb25e18a","/news/a.html",{"c":["实验室活动"],"e":"<p>aaaaaaa<br>\nhsdjkfhjksd</p>\n","y":"a","t":"asas","i":"circle-info"},[":md"]],
  ["v-79185279","/project/chest_radiograph.html",{"y":"p","t":"胸部 X 射线肺部疾病检测"},[":md"]],
  ["v-0b0ced43","/project/pulmonary_nodule.html",{"y":"p","t":"肺部结节智能诊断"},[":md"]],
  ["v-28eb9c50","/teamindex/xhding.html",{"y":"p","t":"丁兴号"},[":md"]],
  ["v-e821202e","/teamindex/xttu.html",{"y":"p","t":"涂晓彤"},[":md"]],
  ["v-19f0dcb2","/teamindex/yhuang.html",{"y":"p","t":"黄悦"},[":md"]],
  ["v-4c706ad6","/teamindex/zlxiao.html",{"y":"p","t":"肖珍龙"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-4159c4b0","/dataset/",{"y":"p","t":"Dataset"},[]],
  ["v-1500d063","/news/",{"y":"p","t":"News"},[]],
  ["v-c9bbfba2","/project/",{"y":"p","t":"Project"},[]],
  ["v-c7beec1a","/teamindex/",{"y":"p","t":"Teamindex"},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":0},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":0},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":0},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":0},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":0},[]],
  ["v-1037554b","/category/%E5%AE%9E%E9%AA%8C%E5%AE%A4%E6%B4%BB%E5%8A%A8/",{"y":"p","t":"实验室活动 分类","I":0},["/category/实验室活动/"]],
]
